version: 2.1
# Orchestrate or schedule a set of jobs
workflows:
  main:
    jobs:
      - test

jobs:
  test:
    machine:
      image: ubuntu-2004:202011-01
    resource_class: arm-medium
    steps:
      - run: echo "im a machine provisioned job"
