version: 2.1
# Orchestrate or schedule a set of jobs
workflows:
  main:
    jobs:
      - test

jobs:
  test:
    machine:
      image: ubuntu-2004:202107-02
    resource_class: large
    steps:
      - run: echo "im a machine provisioned job"
      - store_results
      - run: sleep 3600

commands:
  store_results:
    steps:
      - run:
          name: store stuff
          when: always
          command: |
            echo "i'm an artifact" > result
      - store_artifacts:
          path: result
