version: 2.1
# Orchestrate or schedule a set of jobs
workflows:
  main:
    jobs:
      - test

jobs:
  test:
    machine: true
    steps:
      - run: echo "hello"
      - store_results
      - run: sleep 100

commands:
  store_results:
    steps:
      - run:
          name: store stuff
          when: always
          command: |
            echo "i'm an artifact" > result
      - store_artifacts:
          path: result
